version: '3.8'

services:
  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./data_filtered:/app/data_filtered
      - ./messages:/app/messages

networks:
  default:
    driver: bridge
